apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/address-pool: sdf-services
    metallb.io/ip-allocated-from-pool: sdf-services
  name: usdf-butler-embargo-svc
  namespace: embargo-prod
spec:
  clusterIP: 10.103.181.208
  clusterIPs:
  - 10.103.181.208
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 172.24.5.77
  ports:
  - name: pgbouncer
    nodePort: 31413
    port: 5432
  selector:
    cnpg.io/cluster: usdf-butler-embargo
    role: primary
  type: LoadBalancer
