apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/address-pool: sdf-services
    metallb.io/ip-allocated-from-pool: sdf-services
    metallb.io/loadBalancerIPs: 172.24.5.76
  name: embargo-db-svc-old
  namespace: embargo-prod
spec:
  loadBalancerIPs: 172.24.5.76
  allocateLoadBalancerNodePorts: false
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: pgbouncer
    port: 5432
  selector:
    cnpg.io/cluster: embargo-db
    cnpg.io/instanceRole: primary
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/address-pool: sdf-services
    metallb.io/ip-allocated-from-pool: sdf-services
    metallb.io/loadBalancerIPs: 172.24.5.254
  name: embargo-db-svc-old2
  namespace: embargo-prod
spec:
  loadBalancerIPs: 172.24.5.254
  allocateLoadBalancerNodePorts: false
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: pgbouncer
    port: 5432
  selector:
    cnpg.io/cluster: embargo-db
    cnpg.io/instanceRole: primary
  type: LoadBalancer
