
resources:
- ns.yaml
# cnpg
- cnpg-butler-embargo-database.yaml
- cnpg-butler-embargo-pooler.yaml
- backup.yaml
- db-svc.yaml

secretGenerator:
- name: usdf-butler-embargo-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password
  
- name: s3-creds
  options:
    disableNameSuffixHash: true
  files:
  - ACCESS_KEY_ID=etc/.secrets/access-key
  - ACCESS_SECRET_KEY=etc/.secrets/secret-key


namespace: embargo-prod
commonLabels:
  env: embargo-prod
  app: butler-embargo
  namespace: embargo-prod
