apiVersion: v1
kind: Service
metadata:
  name: usdf-butler3-db-svc
  namespace: prod2
  annotations:
    metallb.universe.tf/address-pool: sdf-rubin-ingest
spec:
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: usdf-butler3
    role: primary
  sessionAffinity: None
  type: LoadBalancer
