
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: embargo-db
  namespace: embargo-dev
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  enablePDB: false
  bootstrap:
    pg_basebackup:
      source: old-primary
  imageName: ghcr.io/lsst-sqre/cnpg-postgres-images:16.3
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true'
  monitoring:
    enablePodMonitor: true
  nodeMaintenanceWindow:
    reusePVC: true
  postgresql:
    parameters:
      dynamic_shared_memory_type: posix
      log_destination: csvlog
      log_directory: /controller/log
      log_disconnections: "off"
      log_duration: "off"
      log_filename: postgres
      log_min_duration_statement: 250ms
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_statement: "none"
      log_temp_files: "1"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      maintenance_work_mem: 12GB
      max_connections: "2000"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_wal_size: 256GB
      max_worker_processes: "32"
      min_wal_size: 4GB
      pg_stat_statements.track: "none"
      random_page_cost: "1.1"
      shared_buffers: 8GB
      wal_keep_size: 512MB
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
      work_mem: 320MB
      max_slot_wal_keep_size: "100GB"
      wal_compression: "off"
  resources:
    requests:
      memory: 16Gi
      cpu: 4
    limits:
      memory: 32Gi
      cpu: 8
  storage:
    storageClass: wekafs--sdf-k8s01
    size: 1000Gi
  replica:
    enabled: false
    source: old-primary
  externalClusters:
    - name: old-primary
      connectionParameters:
        host: usdf-butler-embargo-rw
        user: streaming_replica
      sslKey:
        name: usdf-butler-embargo-replication
        key: tls.key
      sslCert:
        name: usdf-butler-embargo-replication
        key: tls.crt
      sslRootCert:
        name: usdf-butler-embargo-ca
        key: ca.crt
