---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: usdf-butler-embargo16-pooler-transaction-rw
spec:
  cluster:
    name: usdf-butler-embargo16
  instances: 3
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "4000"
      default_pool_size: "3000"
      log_connections: "1"
      log_disconnections: "1"
      idle_transaction_timeout: "0"
      server_idle_timeout: "60"
      tcp_keepalive: "1"
      tcp_keepcnt: "1"
      tcp_keepidle: "1"
      tcp_keepintvl: "1"
      tcp_user_timeout: "1000"
  template:
    metadata:
      labels:
        app: pooler
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: pgbouncer
        resources:
          requests:
            cpu: "1"
            memory: 100Mi
          limits:
            cpu: "1"
            memory: 500Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pooler
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: usdf-butler-embargo16-pooler-session-rw
spec:
  cluster:
    name: usdf-butler-embargo16
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "2000"
      default_pool_size: "1000"
      log_connections: "1"
      log_disconnections: "1"
      idle_transaction_timeout: "0"
      server_idle_timeout: "0"
      tcp_keepalive: "1"
      tcp_keepcnt: "1"
      tcp_keepidle: "1"
      tcp_keepintvl: "1"
      tcp_user_timeout: "1000"
  template:
    metadata:
      labels:
        app: pooler
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: pgbouncer
        resources:
          requests:
            cpu: "1"
            memory: 100Mi
          limits:
            cpu: "1"
            memory: 500Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pooler
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  annotations:
  name: usdf-butler-embargo16-pooler-transaction-ro
  namespace: embargo16-prod
spec:
  cluster:
    name: usdf-butler-embargo16
  instances: 3
  pgbouncer:
    parameters:
      default_pool_size: "1000"
      idle_transaction_timeout: "0"
      log_connections: "1"
      log_disconnections: "1"
      max_client_conn: "2000"
      server_idle_timeout: "0"
      tcp_keepalive: "1"
      tcp_keepcnt: "1"
      tcp_keepidle: "1"
      tcp_keepintvl: "1"
      tcp_user_timeout: "5000"
    paused: false
    poolMode: transaction
  serviceTemplate:
    metadata:
      annotations:
        metallb.universe.tf/address-pool: sdf-rubin-ingest
    spec:
      type: LoadBalancer
      loadBalancerIP: '172.24.10.32' #added this line after getting the IP from sdf-rubin-ingest pool
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: pooler
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pooler
            topologyKey: kubernetes.io/hostname
      containers:
      - name: pgbouncer
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: "1"
            memory: 100Mi
  type: ro
