apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: usdf-butler-embargo16
  namespace: embargo16-prod
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: lsstdb1
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: rubin
      secret:
        name: usdf-butler-embargo16-creds
  backup:
    retentionPolicy: "15d"
    barmanObjectStore:
      destinationPath: s3://rubin-usdf-butler-embargo16
      endpointURL: https://s3dfrgw.slac.stanford.edu
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-creds
          key: ACCESS_SECRET_KEY
  bootstrap:
    initdb:
      database: lsstdb1
      owner: rubin
      secret:
        name: usdf-butler-embargo16-creds
  imageName:  ghcr.io/lsst-sqre/cnpg-postgres-images:16.3
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true' 
  monitoring:
    enablePodMonitor: true
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  postgresql:
    parameters:
        dynamic_shared_memory_type: posix
        log_destination: csvlog
        log_directory: /controller/log
        log_disconnections: "off"
        log_duration: "off"
        log_filename: postgres
        log_min_duration_statement: 1000ms
        log_rotation_age: "0"
        log_rotation_size: "0"
        log_statement: all
        log_temp_files: "1"
        log_truncate_on_rotation: "false"
        logging_collector: "on"
        maintenance_work_mem: 12GB
        max_connections: "2000"
        max_parallel_workers: "32"
        max_replication_slots: "32"
        max_wal_size: 256GB
        max_worker_processes: "32"
        min_wal_size: 4GB
        pg_stat_statements.track: "none"
        random_page_cost: "1.1"
        shared_buffers: 64GB
        wal_buffers: 64MB
        wal_keep_size: 512MB
        wal_receiver_timeout: 5s
        wal_sender_timeout: 5s
        work_mem: 320MB
        max_slot_wal_keep_size: "100GB"
        wal_compression: "off"
        checkpoint_timeout: "900"
  resources:
    requests:
      memory: 192Gi
      cpu: 16
    limits:
      memory: 192Gi
      cpu: 32
  storage:
    storageClass: wekafs--sdf-k8s01
    size: 3000Gi
