
resources:
- ns.yaml
# cnpg
- database.yaml
- db-svc.yaml
- db-svc-to-remove.yaml
- pooler-ss-rw-svc.yaml
- pooler-tx-rw-svc.yaml
- pooler-tx-ro-svc.yaml
- backup.yaml
#- object-store.yaml

secretGenerator:
- name: usdf-butler-embargo16-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password

- name: s3-creds
  options:
    disableNameSuffixHash: true
  files:
  - ACCESS_KEY_ID=etc/.secrets/client-id
  - ACCESS_SECRET_KEY=etc/.secrets/client-secret

- name: usdf-butler-embargo16-monitor
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/monitor-user
  - etc/.secrets/monitor-password

namespace: embargo16-prod
