
resources:
- ns.yaml
# cnpg
- database.yaml
- db-svc.yaml
- pooler-tx-rw-svc.yaml
- pooler-ss-rw-svc.yaml
- backup.yaml

secretGenerator:
- name: usdf-butler-dc2-16-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password


- name: s3-creds
  options:
    disableNameSuffixHash: true
  files:
  - ACCESS_KEY_ID=etc/.secrets/client-id
  - ACCESS_SECRET_KEY=etc/.secrets/client-secret


namespace: dc2-16-prod
