apiVersion: v1
kind: Secret
metadata:
  name: usdf-butler-dp1-pg-monitor
  namespace: dp1
type: Opaque
stringData:
  monitor-password: "b230ebbb70ec531d5fcdc98fa5a8696e"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: snap-script
  namespace: dp1
data:
  snap-activity.sql: |
    WITH inserted AS (
      INSERT INTO pg_stat_activity_snap
        SELECT
          now() ts, a.*
        FROM pg_stat_activity a
        WHERE state <> 'idle' and pid <> pg_backend_pid() and usename <> 'streaming_replica'
        RETURNING *
      )
    select row_to_json(inserted.*) from inserted;
  snap-statement.sql: |
    WITH inserted AS (
        INSERT INTO pg_stat_statements_snap
        SELECT now() ts, a.*
        FROM pg_stat_statements a
        WHERE calls > 0
        RETURNING *
    )
    SELECT row_to_json(inserted.*) FROM inserted;
    SELECT pg_stat_statements_reset();
  snap-purge.sql: |
    DELETE FROM pg_stat_activity_snap WHERE ts < now() - interval '14 days';
    DELETE FROM pg_stat_statements_snap WHERE ts < now() - interval '14 days';
    VACUUM (ANALYZE) pg_stat_activity_snap;
    VACUUM (ANALYZE) pg_stat_statements_snap;

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: usdf-butler-dp1-snap-activity
  namespace: dp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snap-activity
  template:
    metadata:
      labels:
        app: snap-activity
    spec:
      restartPolicy: Always
      containers:
      - name: psql
        image: postgres:16
        resources:
              requests:
                memory: 128Mi
                cpu: 100m
              limits:
                memory: 256Mi
                cpu: 200m
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: usdf-butler-dp1-pg-monitor 
              key: monitor-password
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              psql -tq -h usdf-butler-dp1-rw -U monitor_user -d postgres -v ON_ERROR_STOP=1 -f /sql/snap-activity.sql
              sleep 10
            done
        volumeMounts:
          - name: snap-script
            mountPath: /sql
            readOnly: true
      volumes:
        - name: snap-script
          configMap:
            name: snap-script
            defaultMode: 0775
---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: usdf-butler-dp1-snap-statement
  namespace: dp1
spec:
  schedule: "*/10 * * * *"        # every 10 minutes
  concurrencyPolicy: Forbid       # skip if previous job still running
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1             # retry once on failure
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: psql
            image: postgres:16
            resources:
              requests:
                memory: 128Mi
                cpu: 100m
              limits:
                memory: 256Mi
                cpu: 200m
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: usdf-butler-dp1-pg-monitor 
                  key: monitor-password
            command: ["/bin/sh", "-c"]
            args:
              - |
                psql -tq -h usdf-butler-dp1-rw -U monitor_user -d postgres -v ON_ERROR_STOP=1 -f /sql/snap-statement.sql
            volumeMounts:
              - name: snap-script
                mountPath: /sql
                readOnly: true
          volumes:
            - name: snap-script
              configMap:
                name: snap-script
                defaultMode: 0775

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: usdf-butler-dp1-snap-purge
  namespace: dp1
spec:
  schedule: "0 14 * * *"        # daily purge
  concurrencyPolicy: Forbid     # skip if previous job still running
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1             # retry once on failure
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: psql
            image: postgres:16
            resources:
              requests:
                memory: 128Mi
                cpu: 100m
              limits:
                memory: 256Mi
                cpu: 200m
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: usdf-butler-dp1-pg-monitor 
                  key: monitor-password
            command: ["/bin/sh", "-c"]
            args:
              - |
                psql -tq -h usdf-butler-dp1-rw -U monitor_user -d postgres -v ON_ERROR_STOP=1 -f /sql/snap-purge.sql
            volumeMounts:
              - name: snap-script
                mountPath: /sql
                readOnly: true
          volumes:
            - name: snap-script
              configMap:
                name: snap-script
                defaultMode: 0775
