
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dp03-2
  namespace: dp03
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: app
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: app
  backup:
    barmanObjectStore:
      destinationPath: s3://rubin-usdf-pg-catalogs
      endpointURL: https://s3dfrgw.slac.stanford.edu
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: s3-creds
        inheritFromIAMRole: false
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: s3-creds
    retentionPolicy: 15d
    target: prefer-standby
  imageName: lsstsqre/cloudnative-pg:14.4
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true'
  monitoring:
    enablePodMonitor: true
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  postgresql:
    parameters:
      log_disconnections: "on"
      log_duration: "on"
      log_min_duration_statement: 250ms
      log_statement: all
      log_temp_files: "1"
      maintenance_work_mem: 2GB
      max_connections: "1000"
      max_wal_size: 16GB
      min_wal_size: 4GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      random_page_cost: "1.1"
      shared_buffers: 16GB
      work_mem: 160MB
    pg_hba:
    - host replication postgres all md5
    - host replicatiom postgres all scram-sha-256

  resources:
    requests:
      memory: 32Gi
      cpu: 4
    limits:
      memory: 64Gi
      cpu: 16
  storage:
    storageClass: wekafs--sdf-k8s01
    size: 2000Gi
