apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: usdf-butler-prompt16
  namespace: prompt16-prod
spec:
  affinity:
    podAntiAffinityType: preferred
  backup:
    barmanObjectStore:
      wal:
        compression: gzip
        maxParallel: 8   
      destinationPath: s3://rubin-usdf-butler-prompt16
      endpointURL: https://s3dfrgw.slac.stanford.edu
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: s3-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: s3-creds
    retentionPolicy: 15d
    target: prefer-standby
  bootstrap:
    initdb:
      database: lsstdb1
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: rubin
      secret:
        name: usdf-butler-prompt16-creds
  enablePDB: true
  enableSuperuserAccess: false
  failoverDelay: 0
  imageName: ghcr.io/lsst-sqre/cnpg-postgres-images:16.3
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
  instances: 2
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      full_page_writes: "on"
      log_destination: csvlog
      log_directory: /controller/log
      log_disconnections: "off"
      log_duration: "off"
      log_filename: postgres
      log_min_duration_statement: 250ms
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_statement: none
      log_temp_files: "1"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      checkpoint_timeout: "900"
      maintenance_work_mem: 12GB
      max_connections: "2000"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_slot_wal_keep_size: 100GB
      max_wal_size: 256GB
      max_worker_processes: "32"
      min_wal_size: 4GB
      pg_stat_statements.track: top
      pg_stat_statements.max: "10000"
      random_page_cost: "1.1"
      shared_buffers: 16GB
      shared_memory_type: mmap
      shared_preload_libraries: ""
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_compression: "off"
      wal_keep_size: 512MB
      wal_level: logical
      wal_log_hints: "on"
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
      work_mem: 320MB
      effective_cache_size: 24GB
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources:
    limits:
      cpu: "8"
      memory: 32Gi
    requests:
      cpu: "8"
      memory: 32Gi
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  storage:
    resizeInUseVolumes: true
    size: 1000Gi
    storageClass: wekafs--sdf-k8s01
  walStorage:
    resizeInUseVolumes: true
    storageClass: wekafs--sdf-k8s01
    size: 320Gi
  switchoverDelay: 3600
