
resources:
- ns.yaml
# cnpg
- database.yaml
- pooler.yaml
- lb-svc.yaml
- backup.yaml

secretGenerator:
- name: usdf-butler-misc16-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password

- name: s3-creds
  options:
    disableNameSuffixHash: true
  files:
  - ACCESS_KEY_ID=etc/.secrets/client-id
  - ACCESS_SECRET_KEY=etc/.secrets/client-secret

namespace: misc16-prod
