---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: usdf-butler-teststand-pooler-transaction-rw
spec:
  cluster:
    name: usdf-butler-teststand
  instances: 3
  type: rw
  serviceTemplate:
    metadata:
      annotations:
        metallb.universe.tf/address-pool: sdf-services
    spec:
      type: LoadBalancer


  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "2000"
      default_pool_size: "1000"
      log_connections: "1"
      log_disconnections: "1"
      idle_transaction_timeout: "0"
      server_idle_timeout: "0"
      tcp_keepalive: "1"
      tcp_keepcnt: "1"
      tcp_keepidle: "1"
      tcp_keepintvl: "1"
      tcp_user_timeout: "1000"

  template:
    metadata:
      labels:
        app: pooler
      annotations:
        prometheus.io/scrape: 'true'
    
    spec:
      containers:
      - name: pgbouncer
        resources:
          requests:
            cpu: "1"
            memory: 100Mi
          limits:
            cpu: "1"
            memory: 500Mi

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pooler
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: usdf-butler-teststand-pooler-session-rw
spec:
  cluster:
    name: usdf-butler-teststand
  instances: 3
  type: rw
  serviceTemplate:
    metadata:
      annotations:
        metallb.universe.tf/address-pool: sdf-services
    spec:
      type: LoadBalancer

  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "2000"
      default_pool_size: "1000"
      log_connections: "1"
      log_disconnections: "1"
      idle_transaction_timeout: "0"
      server_idle_timeout: "0"
      tcp_keepalive: "1"
      tcp_keepcnt: "1"
      tcp_keepidle: "1"
      tcp_keepintvl: "1"
      tcp_user_timeout: "1000"

  template:
    metadata:
      labels:
        app: pooler
      annotations:
        prometheus.io/scrape: 'true'
    
    spec:
      containers:
      - name: pgbouncer
        resources:
          requests:
            cpu: "1"
            memory: 100Mi
          limits:
            cpu: "1"
            memory: 500Mi

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pooler
            topologyKey: "kubernetes.io/hostname"
---