apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/address-pool: sdf-services
    metallb.io/ip-allocated-from-pool: sdf-services
    metallb.io/loadBalancerIP: 172.24.5.69
  name: usdf-butler-dc2-16-svc
  namespace: dc2-16-prod
spec:
  allocateLoadBalancerNodePorts: false
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: pgbouncer
    port: 5432
  selector:
    cnpg.io/cluster: usdf-butler-dc2-16
    role: primary
  type: LoadBalancer
