apiVersion: v1
kind: Service
metadata:
  name: usdf-butler-dc2-16-svc
  namespace: dc2-16-prod
  annotations:
    metallb.io/address-pool: sdf-services
spec:
  allocateLoadBalancerNodePorts: false
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: usdf-butler-dc2-16
    role: primary
  sessionAffinity: None
  type: LoadBalancer

