apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: usdf-butler-teststand-backup
  namespace: teststand-prod
spec:
  immediate: true
  schedule: "0 0 10 * * *"
  backupOwnerReference: self
  cluster:
    name: usdf-butler-teststand
