---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnpg-controller-manager
  namespace: cnpg-system
spec:
  template:
    spec:
      containers:
        - name: manager
          resources:
            limits:
              memory: 2Gi
