apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: embargo-db
  namespace: embargo-prod
spec:
  affinity:
    podAntiAffinityType: preferred
  bootstrap:
    pg_basebackup:
      source: old-primary
  enablePDB: true
  enableSuperuserAccess: false
  failoverDelay: 0
  imageName: ghcr.io/lsst-sqre/cnpg-postgres-images:16.3
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
  instances: 1
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      checkpoint_timeout: "3600"
      dynamic_shared_memory_type: posix
      full_page_writes: "on"
      idle_in_transaction_session_timeout: "14400000"
      log_destination: csvlog
      log_directory: /controller/log
      log_disconnections: "off"
      log_duration: "off"
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_statement: none
      log_temp_files: "1"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      maintenance_work_mem: 12GB
      max_connections: "2000"
      max_locks_per_transaction: "512"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_slot_wal_keep_size: 256GB
      max_wal_size: 256GB
      max_worker_processes: "32"
      min_wal_size: 64GB
      pg_stat_statements.track: none
      random_page_cost: "1.1"
      shared_buffers: 32GB
      shared_memory_type: mmap
      shared_preload_libraries: ""
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      statement_timeout: "14400000"
      wal_buffers: 64MB
      wal_compression: "off"
      wal_keep_size: 64GB
      wal_level: logical
      wal_log_hints: "on"
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
      work_mem: 320MB
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources:
    limits:
      cpu: "8"
      memory: 64Gi
    requests:
      cpu: "8"
      memory: 64Gi
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  storage:
    resizeInUseVolumes: true
    size: 3000Gi
    storageClass: wekafs--sdf-k8s01
  switchoverDelay: 3600
  replica:
    enabled: true
    source: old-primary
  externalClusters:
    - name: old-primary
      connectionParameters:
        host: usdf-butler-embargo16-rw.embargo16-prod
        user: streaming_replica
      sslKey:
        name: usdf-butler-embargo16-replication
        key: tls.key
      sslCert:
        name: usdf-butler-embargo16-replication
        key: tls.crt
      sslRootCert:
        name: usdf-butler-embargo16-ca
        key: ca.crt
